### ISSUE TITLE
I am trying to use microsoft graph auth library preview. I amable to initialize the graphClient but unable to get data.I am getting unauthorized 401. 

### ISSUE THREAD

**Issue by victormarcus** [microsoftgraph/msgraph-sdk-java-auth#26]
I am trying to use microsoft graph auth library preview. I am getting unauthorized 401. **"code": "InvalidAuthenticationToken", "message": "CompactToken parsing failed with error code: 80049217",** I am passing the scope "https://graph.microsoft.com/.default". I have admin consent granted for applicaion permissions :

> user.read.all, mail.read
![Capture](https://user-images.githubusercontent.com/36796254/73627169-97305f80-4671-11ea-8e16-b5540fe1916e.PNG)
` List<String> scopes = new ArrayList<String>();
    scopes.add("User.Read.All");

ClientCredentialProvider authProvider = new ClientCredentialProvider(app-Id, 
            scopes_list,
            client-Secret,
            tenantId, NationalCloud.Global);

IgraphClient graphClient = GraphServiceClient.builder().authenticationProvider(authProvider).logger(logger)
                .buildClient();

IUserCollectionPage users = graphClient.users()
            .buildRequest()
            .get();
    List<User> usersList = users.getCurrentPage();
    for(User user : usersList) {
        System.out.println(user.displayName);
    }`

**Comment by kumbhaj** [comment]
@NakulSabharwal, @MIchaelMainer Can you please address this issue. It's not been resolved on Github.

**Comment by MIchaelMainer** [comment]
@kumbhaj Nakul is no longer working on this project. We need to assign another dev to this project so that we can resolve this and other issues.

**Comment by kumbhaj** [comment]
@MIchaelMainer Thanks for the response. I am counting on you.

**Comment by victormarcus** [comment]
Apart from the above error I also get: 

> `OAuthProblemException{error='unsupported_response_type', description='Invalid response! Response body is not application/json encoded', uri='null', state='null', scope='null', redirectUri='null', responseStatus=0, parameters={}}
	at org.apache.oltu.oauth2.common.exception.OAuthProblemException.error(OAuthProblemException.java:63)
	at org.apache.oltu.oauth2.client.response.OAuthJSONAccessTokenResponse.setBody(OAuthJSONAccessTokenResponse.java:76)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:92)
	at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(OAuthAccessTokenResponse.java:65)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:101)
	at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(OAuthAccessTokenResponse.java:60)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:120)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory.createCustomResponse(OAuthClientResponseFactory.java:82)
	at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:111)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:71)
	at com.microsoft.graph.auth.confidentialClient.ClientCredentialProvider.getAccessTokenNewRequest(ClientCredentialProvider.java:102)
	at com.microsoft.graph.auth.confidentialClient.ClientCredentialProvider.getAcccessToken(ClientCredentialProvider.java:67)
	at com.microsoft.graph.auth.confidentialClient.ClientCredentialProvider.authenticateRequest(ClientCredentialProvider.java:49)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:232)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:89)
	at com.microsoft.graph.requests.extensions.UserCollectionRequest.get(UserCollectionRequest.java:52)
	at GraphAuth_V1.main(GraphAuth_V1.java:24)`

**Comment by kumbhaj** [comment]
https://stackoverflow.com/questions/43574573/apache-oltu-unsupported-response-type
Maybe you are missing this:
`request.addHeader("Accept", "application/json");
request.addHeader("Content-Type", "application/json");`

**Comment by victormarcus** [comment]
The issue is now resolved. Maybe be because of recent changes
