### ISSUE TITLE
CompactToken parsing failed with error code: 80049217

### ISSUE THREAD

**Issue by victormarcus** [microsoftgraph/msgraph-sdk-java-auth#61]
We are using the following libraries:
1. microsoft-sdk-java-auth 0.2.0
2. microsoft-graph 2.3.1
3. microsoft-graph-core 1.0.5

We get this error sometimes while fetching any user's details. 
ex- https://graph.microsoft.com/v1.0/users/email-addr@domain.com

Trace:
com.microsoft.graph.http.GraphServiceException: Error code: InvalidAuthenticationToken
Error message: CompactToken parsing failed with error code: 80049217

GET https://graph.microsoft.com/v1.0/users/email-addr@domain.com
SdkVersion : graph-java/v2.3.1
Authorization : [PII_REDACTED]

401 : Unauthorized
com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:501)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:503)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:423)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:345)
	at com.microsoft.graph.requests.extensions.UserRequest.get(UserRequest.java:171)

**Comment by MIchaelMainer** [comment]
Does it reproduce on the same users? Is it possible that there are users in an on-premise linked AD in your organization?
