### ISSUE TITLE
Java SDK - ClientCredentialProvider is throwing a certificate error during http request

### ISSUE THREAD

**Issue by talasj** [microsoftgraph/msgraph-sdk-java-auth#62]
Posting a calendar event using ClientCredentialProvider is throwing a certificate error during http request. Am I missing any configuiration changes? Any help is appreciated.

ClientCredentialProvider authProvider = new ClientCredentialProvider("xxxx", 
				Arrays.asList("https://graph.microsoft.com/.default"), "xxc", "aaa", NationalCloud.Global);
DefaultLogger logger = new DefaultLogger();
        logger.setLoggingLevel(LoggerLevel.DEBUG);
        
		IGraphServiceClient graphClient = GraphServiceClient
						.builder()
						.authenticationProvider(authProvider)
						.logger(logger)
						.buildClient();
LinkedList<Option> requestOptions = new LinkedList<Option>();
		requestOptions.add(new HeaderOption("Prefer", "outlook.timezone=\"Pacific Standard Time\""));

		Event event = new Event();
		event.subject = "Let's go for lunch";
		ItemBody body = new ItemBody();
		body.contentType = BodyType.HTML;
		body.content = "Does noon work for you?";
		event.body = body;
		DateTimeTimeZone start = new DateTimeTimeZone();
		start.dateTime = "2017-04-15T12:00:00";
		start.timeZone = "Pacific Standard Time";
		event.start = start;
		DateTimeTimeZone end = new DateTimeTimeZone();
		end.dateTime = "2017-04-15T14:00:00";
		end.timeZone = "Pacific Standard Time";
		event.end = end;
		Location location = new Location();
		location.displayName = "Test Event";
		event.location = location;
		LinkedList<Attendee> attendeesList = new LinkedList<Attendee>();
		Attendee attendees = new Attendee();
		EmailAddress emailAddress = new EmailAddress();
		emailAddress.address = "test@email.com";
		emailAddress.name = "some name";
		attendees.emailAddress = emailAddress;
		attendees.type = AttendeeType.REQUIRED;
		attendeesList.add(attendees);
		event.attendees = attendeesList;
		event.allowNewTimeProposals = true;
		event.transactionId = "asas";

		
		Event event1 = new Event();
        event1.subject = "Evento de pruebas";

        String timeZone = "Pacific Standard Time";
        DateTimeTimeZone date = new DateTimeTimeZone();
        date.timeZone = timeZone;

        date.dateTime = "2020-08-15T10:00:00";
        date.dateTime = "2020-08-15T15:00:00";
        event1.start = date;
        event1.end = date;
        
		try
		{
		graphClient.me().events()
			.buildRequest( requestOptions )
			.post(event1);
		}
		catch (Exception e){
			System.out.println("Error: " + e.getMessage());
			e.printStackTrace();
		}

com.microsoft.graph.core.ClientException: Error during http request
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:471)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:345)
	at com.microsoft.graph.requests.extensions.EventRequest.post(EventRequest.java:135)
	at com.microsoft.graph.requests.extensions.EventCollectionRequest.post(EventCollectionRequest.java:75)
	at GraphiAPITest.main(GraphiAPITest.java:216)
Caused by: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is: 
	java.security.cert.CertPathValidatorException: The certificate issued by CN=DigiCert Global Root G2, OU=www.digicert.com, O=DigiCert Inc, C=US is not trusted; internal cause is: 
	java.security.cert.CertPathValidatorException: Certificate chaining error
	at com.ibm.jsse2.j.a(j.java:3)
	at com.ibm.jsse2.as.a(as.java:213)
	at com.ibm.jsse2.C.a(C.java:339)
	at com.ibm.jsse2.C.a(C.java:248)
	at com.ibm.jsse2.D.a(D.java:291)
	at com.ibm.jsse2.D.a(D.java:217)
	at com.ibm.jsse2.C.r(C.java:373)
	at com.ibm.jsse2.C.a(C.java:352)
	at com.ibm.jsse2.as.a(as.java:752)
	at com.ibm.jsse2.as.i(as.java:338)
	at com.ibm.jsse2.as.a(as.java:711)
	at com.ibm.jsse2.as.startHandshake(as.java:454)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.microsoft.graph.httpcore.RedirectHandler.intercept(RedirectHandler.java:123)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.microsoft.graph.httpcore.RetryHandler.intercept(RetryHandler.java:140)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:31)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:37)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall.execute(RealCall.java:92)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:398)
	... 6 more

**Comment by MIchaelMainer** [comment]
Can you investigate the validity of the certificates you are using for your application?
